#+title: Заметки
#+LANGUAGE: ru
#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS: [a4paper,fleqn,12pt]
#+LATEX_HEADER: \usepackage[lmargin=15mm, rmargin=15mm, tmargin=2cm, bmargin=2cm]{geometry}

* Представление данных
В общем виде задача ЛП имеет вид
\[
C^{T}[N] \cdot x[N] \to \min
\]
\begin{cases}
A[M_{1},N]\cdot x[N] \geq b[M_{1}]\\
A[M_{2},N] \cdot x[N] = b[M_{2}]\\
x[N_{1}] \geq 0
\end{cases}
** Чтение из файла.
1. В первой строчке размерность задачи: кол-во переменных и кол-во ограничений $m,n$
2. Строка в которой записаны разделённые запятой коэфициенты функции цели (предполагается минимизация)
3. $m$ строк, в которых $n$ разделённых запятой коэфициентов, одно из ={GT,LT,EQ}=, означающее $\ge,\le,=$, свободный член.
4. до $n$ индексов, означающие переменные без ограничения на знак
*** Пример
Пример в отчёт включать скорее всего не стоит, но про представление я бы написал, в частности то, что задачи в
канонической форме генерируются из общей

Задача (если пойдёт в отчёт, это будет с задачей, которую мы используем)
\[
x_{1} + x_{2} + x_{3} \to \min
\]
\begin{cases}
3x_{1} - 5x_{2} + x_{3} \geq 3\\
x_{1} + x_{2} - x_{3} \leq 5\\
8x_{1} + x_{2} + 5x_{3} = 11\\
x_{1} \geq 0 , x_{2} \geq 0
\end{cases}

Будет записана как
#+begin_src csv
3,3
1,1,1
3,-5,1,GT,3
1,1,-1,LT,5
8,1,5,EQ,11
3
#+end_src
** Предобработка
По общей форме задачи генерируется каноническая форма прямой задачи и общая \to каноническая форма двойственной задачи

Каноническая форма хранится в виде вектора коэфициентов функции цели, матрицы коэфициентов ограничений и столбца
свободных членов.
* Симплекс-метод
Решение СЛАУ и преобразование матриц к верхнетреугольному виду для облегчения вычисления определителя ("наивный"
рекурсивный алгоритм очевидно не подходит для задач большой размерности) использует метод отражений, так как он является
точным и уже был реализован в 3м семестре. При решении СЛАУ к ответу приходим, используя обратный ход метода Гаусса.
Матрица преобразований сохраняется для того, чтобы на последующих итерациях можно было не решать СЛАУ заново, перейти
простыми преобразованиями.
** Начальное приближение
Начальное приближение находится с помощью решения симплекс-методом вспомогательной задачи (метод иск. базиса)

Теория об этом. Последние пол страницы методички.
** Итерация симплекс-метода
Теория.
* Перебор крайних точек
